#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul  7 14:31:56 2017

@author: Matthew H. Sears
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.spatial import ConvexHull


# Globals
X_MAX = 100       # Width of reference image in pixels
Y_MAX = 100       # Height of reference image in pixels
PERIOD = 3000     # Time period (in milliseconds) to calculate convex hull area


# Read in the data file (note that header names are important at this time)
data = pd.read_excel('DummyData.xlsx', header = 0)

# Select only the x and y coordinates
points = data.iloc[:, :2]

# Normalize coordinates based upon image size
imageSize = [X_MAX, Y_MAX]
points = points/imageSize

"""
# Define the getFinishRow function
def getFinishRow(times, startRow, period):
    finishRow = 0
    for row in range(startRow, len(times)):
        if times.iloc[row] - times.iloc[startRow] > period:
            finishRow = row -1
            break
    return finishRow
"""

# Define the getStartRow function
def getStartRow(times, finishRow, period):
    startRow = False
    for row in range(finishRow, -1, -1):
        if times.iloc[finishRow] - times.iloc[row] > period:
            startRow = row + 1
            break
    return startRow
   
# Calculate time steps
times = data['totaltime']

for row in range(len(times) - 1, -1, -1):
    startRow = getStartRow(times, row, PERIOD)
    if(startRow):
        data.set_value(row, 'startRow', startRow)
        data.set_value(row, 'rowCount', row - startRow)
        data.set_value(row, 'period', times.iloc[row] - times.iloc[startRow])

"""
# Plot only the points within the time period
plotPoints = points[startRow:finishRow+1]
plotPoints = plotPoints.as_matrix()

# Draw convex hull for first time period
hull = ConvexHull(plotPoints)

plt.title(str(finishTime) + " ms")
plt.plot(plotPoints[:,0], plotPoints[:,1], 'o')
for simplex in hull.simplices:
    plt.plot(plotPoints[simplex, 0], plotPoints[simplex, 1], 'k-')

"""