#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jul  7 14:31:56 2017

@author: Matthew H. Sears
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.spatial import ConvexHull


# Globals
xMax = 100       # Width of reference image in pixels
yMax = 100       # Height of reference image in pixels
period = 3000     # Time period (in milliseconds) to calculate convex hull area


# Read in the data file (note that header names are important at this time)
data = pd.read_excel('DummyData.xlsx', header = 0)

# Select only the x and y coordinates
points = data.iloc[:, :2]

# Normalize coordinates based upon image size
imageSize = [xMax, yMax]
points = points/imageSize

# Select first time period
ttime = data['totaltime']
startRow = 0
row = startRow

for timestamp in ttime:
    if timestamp > period:
        finishRow = row -1
#        row = ttime[ttime == timestamp].index[0]
        print(finishRow)
        print(ttime[finishRow])
        break
    row += 1

plotPoints = points[startRow:finishRow+1]
plotPoints = plotPoints.as_matrix()

# Draw convex hull for first time period
hull = ConvexHull(plotPoints)

plotPoints[:,0]


plt.plot(plotPoints[:,0], plotPoints[:,1], 'o')
for simplex in hull.simplices:
    plt.plot(plotPoints[simplex, 0], plotPoints[simplex, 1], 'k-')